name: 'GitHub Actions Mirror'

on: [push, delete]

jobs:
  mirror_to_pagure:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ssh://git@pagure.io/rules.git
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}
